<a href="https://colab.research.google.com/github/classofai/AIPND/blob/NumPy/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import time 
import numpy as np

In [0]:
x = np.random.random(100000000)

In [0]:
start = time.time()
sum(x)/len(x)
print(time.time() - start)

8.789205551147461


In [0]:
start = time.time()
np.mean(x)
print(time.time() - start)

0.12996768951416016


In [0]:
x = np.array([1, 2, 3, 4, 5])

In [0]:
print(type(x))


<class 'numpy.ndarray'>


In [0]:
x.dtype

dtype('int64')

In [0]:
x.shape

(5,)

In [0]:
Y  = np.array([[1, 2, 3],[4 ,5 ,6],[7 , 8, 9], [9, 10, 11]])

In [0]:
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]


In [0]:
Y.shape

(4, 3)

In [0]:
Y.size

12

In [0]:
x = np.array(['Hello', 'World'])
print(x)

['Hello' 'World']


In [0]:
print('shape', x.shape)
print('type', type(x))
print('dtype', x.dtype)

shape (2,)
type <class 'numpy.ndarray'>
dtype <U5


In [0]:
x = np.array([1, 2, 'World'])
print(x)
print('shape: ', x.shape)
print('type: ', type(x))
print('dtype: ', x.dtype)

['1' '2' 'World']
shape:  (3,)
type:  <class 'numpy.ndarray'>
dtype:  <U21


In [0]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [0]:
x = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(x)
print('dtype: ', x.dtype)

[1 2 3]
dtype:  int64


In [0]:
x = np.array([1, 2, 3, 4, 5])
np.save('my_array', x)

In [0]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]
